### ISSUE TITLE
Invisible response text

### ISSUE THREAD

**Issue by bhoward** [AgentAITechnologies/apex#4]
Some responses are invisible, and only show up when I select the text. See attached image (second response has been highlighted).
<img width="877" alt="Screenshot 2024-10-22 at 8 48 47 PM" src="https://github.com/user-attachments/assets/19dd2639-5472-42fb-9f26-3cb10fbb5fba">

**Comment by MysteryMooCows** [comment]
Resolved in commits on
- main branch [c0fca1d]
- anthropic-computer-use branch [04af0bb]

Edit:
Removed uses of [white] format specifier
